WebInterface/Models/CreateManyViewModel.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using UserHelperCL.Models;

namespace WebInterface.Models
{
    public class CreateManyViewModel
    {

        public string UserNamePrefix { get; set; }
        public int UserNameSuffix { get; set; }
        public int TeamId { get; set; }
        public Team Team { get; set; }
        public string StudentNames { get; set; }
        public int CredentialsId { get; set; }
        public Credentials Credentials { get; set; }
    }
}

WebInterface/Controllers/ServerTeamController.cs
using iTextSharp.text;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserHelperCL;
using UserHelperCL.Database;
using UserHelperCL.Models;

namespace WebInterface.Controllers
{
    [Authorize(Roles="Administrator")]
    public class ServerTeamController : Controller
    {
        StudentsModel db = new StudentsModel();
        UserInteraction interaction = new UserInteraction();
        // GET: ServerTeam
        public ActionResult Index()
        {
            return View(db.Teams.ToList());
        }

        public ActionResult Create()
        {
            Team t = new Team();
            return View(t);
        }

        [HttpPost]
        public ActionResult Create(Team t)
        {
            t.CreatedDate = DateTime.Now;
            db.Teams.Add(t);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            return View(db.Teams.Find(id));
        }

        public ActionResult Edit(int id){
        
            Team toEdit = db.Teams.Find(id);
            return View(toEdit);
        }

        [HttpPost]
        public ActionResult Edit(Team team)
        {
            Team t = db.Teams.Find(team.TeamId);
            if (TryUpdateModel<Team>(t))
            {
                try
                {
                    db.Entry(t).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error updating model " + ex.Message);
                }
            }
            return RedirectToAction("Index");
        }


        public ActionResult Delete(int? id)
        {
            Team t = db.Teams.Find(id);
            return View(t);
        }
        [HttpPost]
        public ActionResult Delete(int id)
        {
            
            interaction.DeleteTeam(id);
            
          
            return RedirectToAction("Index");
        }


        public ActionResult Print(int id)
        {
            Team t = db.Teams.Find(id);
            return View(t);
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                interaction.Dispose();   
                db.Dispose();
            }
            base.Dispose(disposing);
        }

    }
}

WebInterface/Controllers/ServerUserController.cs
using System;
using System.Collections.Generic;
using System.DirectoryServices.AccountManagement;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using UserHelperCL;
using UserHelperCL.Database;
using UserHelperCL.Models;
using UserHelperCL.UserFunctions;
using WebInterface.Models;

namespace WebInterface.Controllers
{
    [Authorize(Roles = "Administrator")]
    public class ServerUserController : Controller
    {
        StudentsModel db = new StudentsModel();
        UserInteraction interaction = new UserInteraction();
        // GET: ServerUser
        public ActionResult Index()
        {

            return View(db.Students.Include("Team").Include("Credentials").ToList());
        }


        public ActionResult Create()
        {
            Student student = new Student();
            Credentials cred = new Credentials();
            student.Credentials = cred;
            ViewBag.StartPort = (db.Credentials.Max(x => x.WebsitePort)+1).ToString();
            SelectList list = new SelectList(db.Teams.ToList(), "TeamId", "Name");
            ViewBag.Teams = list;

            PrincipalSearchResult<Principal> groups = interaction.GetUserGroups();
            ViewBag.UserGroup = new SelectList(groups.ToList(),"Name","Name");

            return View(student);
        }
        [HttpPost]
        public ActionResult Create(Student student)
        {
            ViewBag.StartPort = (db.Credentials.Max(x => x.WebsitePort) + 1).ToString();
            student.Credentials.FTPUserName = student.Credentials.DatabaseUserName;
            student.Credentials.FTPPassword = student.Credentials.DatabasePassword;
            interaction.CreateSingleUser(student.Credentials.DatabaseUserName, student.Credentials.DatabasePassword, student.Credentials.WebsitePort, student.Name, student.TeamId, student.Credentials.WindowsUserGroupName, true, true);
            return RedirectToAction("Index");
        }

        public ActionResult CreateMany()
        {
            ViewBag.StartPort = (db.Credentials.Max(x => x.WebsitePort) + 1).ToString();
            CreateManyViewModel vm = new CreateManyViewModel();
            Credentials cred = new Credentials();
            vm.Credentials = cred;

            SelectList list = new SelectList(db.Teams.ToList(), "TeamId", "Name");
            ViewBag.Teams = list;

            PrincipalSearchResult<Principal> groups = interaction.GetUserGroups();
            ViewBag.UserGroup = new SelectList(groups.ToList(), "Name", "Name");

            return View(vm);
        }
        [HttpPost]
        public ActionResult CreateMany(CreateManyViewModel vm)
        {
          
            interaction.CreateMany(vm.UserNamePrefix,vm.UserNameSuffix, vm.Team.TeamId,vm.Credentials.DatabasePassword,vm.Credentials.WebsitePort,vm.Credentials.WindowsUserGroupName, vm.StudentNames, vm.Credentials.DisablePasswordChange,vm.Credentials.PasswordNeverExpires);
            return RedirectToAction("Index");
        }

        public ActionResult Details(int id)
        {
            SelectList list = new SelectList(db.Teams.ToList(), "TeamId", "Name");
            ViewBag.Teams = list;

            PrincipalSearchResult<Principal> groups = interaction.GetUserGroups();

            ViewBag.UserGroup = new SelectList(groups.ToList(), "Name", "Name");

            return View(db.Students.Find(id));
        }
        public ActionResult Edit(int id)
        {
            Student toEdit = db.Students.Find(id);
            return View(toEdit);
        }
        [HttpPost]
        public ActionResult Edit(Student student)
        {
            Student s = db.Students.Find(student.TeamId);
            if (TryUpdateModel<Student>(student))
            {
                try
                {
                    db.Entry(student).State = System.Data.Entity.EntityState.Modified;
                    db.SaveChanges();
                }
                catch (Exception ex)
                {
                    ModelState.AddModelError("", "Error updating model " + ex.Message);
                }
            }
            return RedirectToAction("Index");
          
        }

        public ActionResult Delete(int id)
        {
            Student toDelete = db.Students.Find(id);
            return View(toDelete);
        }

        [HttpPost]
        public ActionResult Delete(int? id)
        {
            int studId = 0;
            if (id != null)
            {
                studId = Convert.ToInt32(id);
            
            try {
                interaction.DeleteUserWebsiteFTPDatabase(studId);
            interaction.GetDbContext().SaveChanges();
            }
            catch (Exception ex)
            {
                Response.Write(ex.Message + "\n" + ex.StackTrace + "\n" + ex.InnerException);
            }
            }
            return RedirectToAction("Index");
        }


        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                interaction.Dispose();
                db.Dispose();
            }
            base.Dispose(disposing);
        }
    }
}

WebInterface/Views/ServerUser/Create.cshtml
@model UserHelperCL.Models.Student

@{
    ViewBag.Title = "Opret enkelt bruger";
}
<div class="well">
    <h2>Opret enkelt bruger</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="row">

            <div class="col-md-12">
                <div class="form-horizontal">
                    <h4>Student</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.Name, "Navn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control floating-label", @placeholder = "Brugerens fulde navn eg. Jens Asger Jensen." }, @autocomplete = "off" })

                            @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.TeamId, "Hold", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.TeamId, (SelectList)ViewBag.Teams, new { @class = "form-control", @autocomplete = "off" })
                            <span class="help-block">Vælg det hold/den klasse brugeren skal tilknyttes.</span>
                            @Html.ValidationMessageFor(model => model.TeamId, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.Credentials.DatabaseUserName, "Brugernavn", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Credentials.DatabaseUserName, new { @class = "form-control floating-label", @placeholder = "Indtast brugernavn til brugeren. Dette brugernavn bliver brugt til både FTP og Database", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.Credentials.DatabaseUserName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Credentials.DatabasePassword, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Credentials.DatabasePassword, new { @class = "form-control floating-label", @placeholder = "Indtast password til brugeren. Dette password bliver brugt til både FTP og Database" })
                            @Html.ValidationMessageFor(model => model.Credentials.DatabasePassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Credentials.WebsitePort, "Port", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Credentials.WebsitePort, new { @class = "form-control floating-label", @placeholder = "Skriv website port. (Den næste port i rækken er valgt sat som standard i feltet)", @Value = ViewBag.StartPort, @autocomplete = "off" })

                            @Html.ValidationMessageFor(model => model.Credentials.WebsitePort, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.Credentials.WindowsUserGroupName, "Windows brugergruppe", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.Credentials.WindowsUserGroupName, (SelectList)ViewBag.UserGroup, new { @class = "form-control" })
                            <span class="help-block">Vælg windows brugergruppe. For FTP adgang, vælg "FTPUsers"</span>

                            @Html.ValidationMessageFor(model => model.Credentials.WindowsUserGroupName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Credentials.DisablePasswordChange, "", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                           
                            
                                    @Html.CheckBoxFor(x => x.Credentials.DisablePasswordChange) Må ikke skifte password
                              
                                @Html.ValidationMessageFor(model => model.Credentials.DisablePasswordChange, "", new { @class = "text-danger" })
                            </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Credentials.PasswordNeverExpires, "", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                           
                                    @Html.CheckBoxFor(x => x.Credentials.PasswordNeverExpires) Password udløber aldrig
                               
                            @Html.ValidationMessageFor(model => model.Credentials.DisablePasswordChange, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>




    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

WebInterface/Views/ServerUser/CreateMany.cshtml
@model WebInterface.Models.CreateManyViewModel

@{
    ViewBag.Title = "Opret mange brugere";
}
<div class="well">
    <h2>Opret mange brugere</h2>
    @using (Html.BeginForm())
    {
        @Html.AntiForgeryToken()
        <div class="row">

            <div class="col-md-12">
                <div class="form-horizontal">
                    <h4>Indtast oplysninger</h4>
                    <hr />
                    @Html.ValidationSummary(true, "", new { @class = "text-danger" })

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserNamePrefix, "Brugernavn Prefiks", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.EditorFor(model => model.UserNamePrefix, new { htmlAttributes = new { @class = "form-control floating-label", @placeholder = "Indtast det som brugernavnene skal starte med", @autocomplete = "off" } })
                            @Html.ValidationMessageFor(model => model.UserNamePrefix, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(model => model.UserNameSuffix, "Brugernavn Suffiks", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.UserNameSuffix, new { @class = "form-control floating-label", @placeholder = "Indtast det tal som brugernavnets endelse starter på eg. 1", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.UserNameSuffix, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Credentials.DatabasePassword, "Password", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Credentials.DatabasePassword, new { @class = "form-control floating-label", @placeholder = "Indtast password for alle brugere", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.Credentials.DatabasePassword, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(model => model.Credentials.WebsitePort, "Port", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextBoxFor(x => x.Credentials.WebsitePort, new { @class = "form-control floating-label", @placeholder = "Indtast den port brugerens website skal starte på", @Value = ViewBag.StartPort, @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.Credentials.WebsitePort, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Team.TeamId, "Hold", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.Team.TeamId, (SelectList)ViewBag.Teams, new { @class = "form-control" })
                            <span class="help-block">Vælg det hold/den klasse brugeren skal tilknyttes.</span>
                            @Html.ValidationMessageFor(model => model.Team.TeamId, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Credentials.WindowsUserGroupName, "Windows brugergruppe", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.DropDownListFor(x => x.Credentials.WindowsUserGroupName, (SelectList)ViewBag.UserGroup, new { @class = "form-control" })
                            <span class="help-block">Vælg windows brugergruppe. For FTP adgang, vælg "FTPUsers"</span>
                            @Html.ValidationMessageFor(model => model.Credentials.WindowsUserGroupName, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.StudentNames, "Fulde navne", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            @Html.TextAreaFor(x => x.StudentNames, new { @class = "form-control floating-label", @rows = 8, @placeholder = "Fulde navne på brugere, disse skal indtastes kommasepereret. eg. Jens Hansen, Knud Jensen", @autocomplete = "off" })
                            @Html.ValidationMessageFor(model => model.StudentNames, "", new { @class = "text-danger" })
                        </div>
                    </div>

                    <div class="form-group">
                        @Html.LabelFor(x => x.Credentials.DisablePasswordChange, "", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                         
                                     
                                    @Html.CheckBoxFor(x => x.Credentials.DisablePasswordChange) Må ikke skifte password
                                
                            @Html.ValidationMessageFor(model => model.Credentials.DisablePasswordChange, "", new { @class = "text-danger" })
                        </div>
                    </div>
                    <div class="form-group">
                        @Html.LabelFor(x => x.Credentials.PasswordNeverExpires, "", htmlAttributes: new { @class = "control-label col-md-2" })
                        <div class="col-md-10">
                            

                                    @Html.CheckBoxFor(x => x.Credentials.PasswordNeverExpires) Password udløber aldrig
                                 
                            @Html.ValidationMessageFor(model => model.Credentials.PasswordNeverExpires, "", new { @class = "text-danger" })
                        </div>
                    </div>



                    <div class="form-group">
                        <div class="col-md-offset-2 col-md-10">
                            <input type="submit" value="Create" class="btn btn-primary" />
                        </div>
                    </div>
                </div>
            </div>
        </div>

    }

    <div>
        @Html.ActionLink("Back to List", "Index")
    </div>
</div>

WebInterface/Views/ServerUser/Delete.cshtml
@model UserHelperCL.Models.Student

@{
    ViewBag.Title = "Slet";
}
<div class="well">
    <h2>Slet bruger</h2>

    <h3>Er du sikker på at du vil slette denne bruger?</h3>
    <div>
        <h4>Student</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.HiddenFor(x => x.StudentId)
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.DatabaseUserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.DatabaseUserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.DatabasePassword)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.DatabasePassword)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.FTPUserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.FTPUserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.FTPPassword)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.FTPPassword)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.WebsitePort)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.WebsitePort)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.WindowsUserGroupName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.WindowsUserGroupName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Team.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Team.Name)
            </dd>



        </dl>

        @using (Html.BeginForm())
        {
            @Html.AntiForgeryToken()

            <div class="form-actions no-color">
                <input type="submit" value="Delete" class="btn btn-default" /> |
                @Html.ActionLink("Back to List", "Index")
            </div>
        }
    </div>
</div>

WebInterface/Views/ServerUser/Details.cshtml
@model UserHelperCL.Models.Student

@{
    ViewBag.Title = "Detaljer";
}
<div class="well">
    <h2>Detaljer</h2>

    <div>
        <h4>Student</h4>
        <hr />
        <dl class="dl-horizontal">
            <dt>
                @Html.DisplayNameFor(model => model.Name)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Name)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.DatabaseUserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.DatabaseUserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.DatabasePassword)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.DatabasePassword)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.FTPUserName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.FTPUserName)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.FTPPassword)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.FTPPassword)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.WebsitePort)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.WebsitePort)
            </dd>
            <dt>
                @Html.DisplayNameFor(model => model.Credentials.WindowsUserGroupName)
            </dt>

            <dd>
                @Html.DisplayFor(model => model.Credentials.WindowsUserGroupName)
            </dd>

            <dt>
                @Html.DisplayNameFor(model => model.Team.Name)
            </dt>

            <dd>
                @Html.ActionLink(Model.Team.Name, "Details", "ServerTeam", new { id = Model.Team.TeamId })

            </dd>



        </dl>
    </div>
    <p>
        @Html.ActionLink("Edit", "Edit", new { id = Model.StudentId }) |
        @Html.ActionLink("Back to List", "Index")
    </p>
</div>

WebInterface/Views/ServerUser/Index.cshtml
@model IEnumerable<UserHelperCL.Models.Student>

@{
    ViewBag.Title = "Index";
}
<div class="well">
    <h2>Brugeroverblik</h2>

    <p>
        @Html.ActionLink("Opret een bruger", "Create")
    </p>
    <p>
        @Html.ActionLink("Opret mange brugere", "CreateMany")
    </p>

    <table class="table table-striped table-hover">
        <tr>
            <th>
                Navn
            </th>

            <th>
                Holdnavn
            </th>

            <th></th>
        </tr>

        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.ActionLink(item.Name, "Details", "ServerUser", new { id = item.StudentId }, null)
                </td>

                <td>
                    @Html.ActionLink(item.Team.Name, "Details", "ServerTeam", new { id = item.Team.TeamId }, null)
                </td>
                <td>
                    Rediger |
                    @Html.ActionLink("Detaljer", "Details", new { id = item.StudentId }) |
                    @Html.ActionLink("Slet", "Delete", new { id = item.StudentId })
                </td>
            </tr>
        }

    </table>
</div>